timeout: 1200s # 20 minutes
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [[ -z "${PROJECT_ID}" ]] || [[ -z "${_REGION}" ]]; then
        echo "ERROR: Required substitutions missing"
        exit 1
      fi
      echo "✓ Configuration validated"
- name: 'bash'
  args: ['scripts/check-node-version.sh']
# 1. Lint shell scripts
- name: 'koalaman/shellcheck-alpine'
  args: 
    - '-x'
    - 'deployment/vm-setup/*.sh'
    - 'deployment/cloud-run/*.sh'
    - 'deployment/gke/*.sh'
    - 'scripts/validation/*.sh'
    - 'scripts/setup/*.sh'
    - 'scripts/maintenance/*.sh'

# 2. Terraform Code Quality Checks
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  args:
    - '-c'
    - |
      terraform fmt -check
      terraform init -backend=false
      terraform validate

# 3. Build Docker
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      NODE_VERSION=$(cat app/.nvmrc)
      docker build --build-arg NODE_VERSION=$$NODE_VERSION \
        -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:${SHORT_SHA} \
        -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:latest \
        ./app

# 4. Push Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:${SHORT_SHA}']

# 4a. Scan for vulnerabilities
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'scan'
  args:
    - 'artifacts'
    - 'docker'
    - 'images'
    - 'scan'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:${SHORT_SHA}'
    - '--format=json'
    - '--region=${_REGION}'
    - '--quiet'
    
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:latest']

# 5. Initialize Terraform
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  secretEnv: ['TF_VAR_tf_state_bucket']
  args:
    - '-c'
    # Use Cloud Build's native substitution for secret environment variables
    - 'echo "Initializing with bucket: ${TF_VAR_tf_state_bucket}" && terraform init -backend-config="bucket=${TF_VAR_tf_state_bucket}"'
# 6. Apply Terraform
- name: 'hashicorp/terraform:1.8.4'
  id: 'apply'
  entrypoint: 'sh'
  dir: 'terraform'
  secretEnv: 
    - 'TF_VAR_duckdns_token'
    - 'TF_VAR_email_address'
    - 'TF_VAR_domain_name'
    - 'TF_VAR_gcs_bucket_name'
    - 'TF_VAR_tf_state_bucket'
    - 'TF_VAR_backup_dir'
    - 'TF_VAR_billing_account_id'
  args:
    - '-c'
    - |
      # Apply changes, but if apply fails, run destroy and exit with error
      terraform apply -auto-approve \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}" \
      || (echo "Terraform apply failed. Rolling back..." && terraform destroy -auto-approve && exit 1)

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/hello-app:latest'

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'gke-apps'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/duckdns_token/versions/latest
    env: 'TF_VAR_duckdns_token'
  - versionName: projects/$PROJECT_ID/secrets/email_address/versions/latest
    env: 'TF_VAR_email_address'
  - versionName: projects/$PROJECT_ID/secrets/domain_name/versions/latest
    env: 'TF_VAR_domain_name'
  - versionName: projects/$PROJECT_ID/secrets/gcs_bucket_name/versions/latest
    env: 'TF_VAR_gcs_bucket_name'
  - versionName: projects/$PROJECT_ID/secrets/tf_state_bucket/versions/latest
    env: 'TF_VAR_tf_state_bucket'
  - versionName: projects/$PROJECT_ID/secrets/backup_dir/versions/latest
    env: 'TF_VAR_backup_dir'
  - versionName: projects/$PROJECT_ID/secrets/billing_account_id/versions/latest
    env: 'TF_VAR_billing_account_id'