steps:
# 1. Lint shell scripts
- name: 'koalaman/shellcheck-alpine'
  args: ['1-gcp-setup/*.sh', '2-host-setup/*.sh']

# 2. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
    - './3-cloud-run-deployment/app'

# 2. Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

# 3. Initialize Terraform
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  secretEnv: ['TF_VAR_tf_state_bucket']
  args:
    - '-c'
    - 'terraform init -backend-config="bucket=$$TF_VAR_tf_state_bucket"'

# 4. Apply Terraform configuration
- name: 'hashicorp/terraform:1.8.4'
  entrypoint: 'sh'
  dir: 'terraform'
  secretEnv: 
    - 'TF_VAR_duckdns_token'
    - 'TF_VAR_email_address'
    - 'TF_VAR_domain_name'
    - 'TF_VAR_gcs_bucket_name'
    - 'TF_VAR_tf_state_bucket'
    - 'TF_VAR_backup_dir'
  args:
    - '-c'
    - |
      terraform apply -auto-approve \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}"

# Store the image name for other builds
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

# Default substitutions
substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'gke-apps'
  _IMAGE_NAME: 'hello-cloud-run'

# Map Secret Manager secrets to Environment Variables
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/duckdns_token/versions/latest
    env: 'TF_VAR_duckdns_token'
  - versionName: projects/$PROJECT_ID/secrets/email_address/versions/latest
    env: 'TF_VAR_email_address'
  - versionName: projects/$PROJECT_ID/secrets/domain_name/versions/latest
    env: 'TF_VAR_domain_name'
  - versionName: projects/$PROJECT_ID/secrets/gcs_bucket_name/versions/latest
    env: 'TF_VAR_gcs_bucket_name'
  - versionName: projects/$PROJECT_ID/secrets/tf_state_bucket/versions/latest
    env: 'TF_VAR_tf_state_bucket'
  - versionName: projects/$PROJECT_ID/secrets/backup_dir/versions/latest
    env: 'TF_VAR_backup_dir'